# Generated by Django 4.1.4 on 2023-01-05 19:25

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('discount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='campaing_images/')),
                ('created', models.DateField(auto_now_add=True)),
                ('slide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategorya Adi')),
                ('image', models.ImageField(null=True, upload_to='category-images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('supper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category')),
            ],
            options={
                'verbose_name': 'Kategorya',
                'verbose_name_plural': 'Kategoryalar',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rəng',
                'verbose_name_plural': 'Rənglər',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(max_length=200, verbose_name='Məzmun')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Haqqinda')),
                ('old_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Kohne Qiymet')),
                ('new_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Hazirki Qiymet')),
                ('cover', imagekit.models.fields.ProcessedImageField(upload_to='products/product-cover-images/', verbose_name='Qapaq Sekili')),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Yerləşdirilmə Tarixi')),
                ('campaings', models.ManyToManyField(related_name='products', to='ecommerce.campaing')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category', verbose_name='Kateqorya')),
                ('colors', models.ManyToManyField(to='ecommerce.color')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ölçü',
                'verbose_name_plural': 'Ölçülər',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='products/product-images/')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Məhsul Şəkili',
                'verbose_name_plural': 'Məhsul Şəkililləri',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='ecommerce.size'),
        ),
    ]
