# Generated by Django 4.1.4 on 2023-01-16 12:19

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Başlıq'),
        ),
        TrigramExtension()
    ]
