# Generated by Django 4.1.4 on 2023-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campaings',
            field=models.ManyToManyField(to='ecommerce.campaing'),
        ),
    ]
