# Generated by Django 4.1.4 on 2023-01-21 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('ecommerce', '0006_alter_product_campaings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star_count',
            new_name='st_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='campaings',
            field=models.ManyToManyField(blank=True, to='ecommerce.campaing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
