# Generated by Django 4.1.4 on 2023-01-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_rename_star_count_review_st_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='st_count',
            new_name='star_count',
        ),
    ]
