# Generated by Django 4.1.4 on 2023-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_st_count_review_star_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_count',
            field=models.IntegerField(),
        ),
    ]
