# Generated by Django 4.1.4 on 2023-01-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_review_star_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_az',
        ),
    ]
