# Generated by Django 4.1.4 on 2023-01-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_rename_title_product_title_az'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='colors_az',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='content_az',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_az',
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
