# Generated by Django 4.1.4 on 2023-01-22 21:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rename_colors_product_colors_az_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors_az',
            new_name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqinda'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqinda'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Məzmun'),
        ),
    ]
