# Generated by Django 4.1.4 on 2023-01-22 22:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_rename_colors_az_product_colors_product_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_tr',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Haqqinda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Məzmun'),
            preserve_default=False,
        ),
    ]
