# Generated by Django 4.1.4 on 2023-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_contact_created_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
