# Generated by Django 4.1.4 on 2023-01-27 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_passwordreset_unique_id_passwordreset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
