# Generated by Django 4.1.4 on 2023-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_passwordreset_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
