# Generated by Django 4.1.4 on 2023-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_passwordreset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.TextField(verbose_name='W94fWj_VgfGYH4lkN_sHgKfQGpCVO2e9f3HT7AVn16VH_cihu_Au3uNgaRFpISZP1SlCULo5YCY6ZlMvjinzOOCZqwguf_fUQ_oTIC_UQug6xDUiWujy4AOcD7ptQ-Pg9YLS7g'),
        ),
    ]
