# Generated by Django 4.1.4 on 2023-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_passwordreset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
